# frontend/Dockerfile.dev
FROM node:18-alpine

ENV NODE_ENV=development

WORKDIR /usr/src/app/frontend

# 依存関係インストール
COPY package*.json ./
COPY package-lock.json ./

RUN npm ci --production=false 

# ソースコードをコピー
COPY . .

# Viteの開発サーバーはデフォルト5173
EXPOSE 5173

CMD ["npm", "run", "dev"]
