services:
  app:
    build: 
      context: .     # ビルドのコンテキストをプロジェクトルートにする
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: . # Gemfile があるディレクトリをマウント
        target: /usr/src/app
    environment:
      # DB接続先情報を環境変数でセット(db サービスと役割が違うが、内容は対応している必要がある)
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=app
      - DB_PASSWORD=app
      - DB_NAME=sample
    # app コンテナ起動前に DB コンテナを起動
    depends_on:
      - db
  db:
    image: mysql:8.1
    ports:
      - "3306:3306"
    # MySQL (DBコンテナ) の初期設定
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=sample
      - TZ=Asia/Tokyo
    volumes:
      - type: volume
        source: db-compose-volume
        target: /var/lib/mysql
      - type: bind
        source: ./docker/db/init
        target: /docker-entrypoint-initdb.d
volumes:
  db-compose-volume: