source "https://rubygems.org"

gem "rack", "~> 2.2"
gem "mysql2", "~> 0.5"
gem "puma", "~> 6.0" # Rack は rackup 実行時に「puma / thin / falcon / webrick などのハンドラ」を探しに行く
gem "bigdecimal", "~> 3.1"
gem "faker", "~> 2.19"
gem 'rake', '13.1.3'
gem 'minitest', '5.15.0'
gem 'rack-test', '1.1.0'